
data_dir: "Hard-coded name of directory with fastq files"
genome_data: "Hard-coded name of genome fasta file"
gtf: "Hard-coded name of gtf file"
gene_info: "Hard-coded name of gene annotation file"

log2FC_cutoff: 2
trimmomatic_threads: 1
star_build_threads: 1
star_map_threads: 2
featureCounts_threads: 1
