read_dir: "config"
genome_fasta: "genome.fasta"
gtf: "genome.gtf"
gene_info: "gene_info.txt"
log2FC_cutoff: 2
trimmomatic_threads: 12
star_build_threads: 12
star_map_threads: 20
featureCounts_threads: 12
